# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1392, 661)
        MainWindow.setStyleSheet("/* =============== COLORES BASE =============== */\n"
"* {\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* =============== FONDO GENERAL =============== */\n"
"QWidget {\n"
"    background-color: #1e1e1e;\n"
"}\n"
"\n"
"/* =============== BOTONES ===================== */\n"
"QPushButton {\n"
"    background-color: #2c2c2c;\n"
"    border: 1px solid #444;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3d3d3d;\n"
"    border: 1px solid #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #555;\n"
"    border: 1px solid #888;\n"
"}\n"
"\n"
"/* =============== BOTONES ICONO ================= */\n"
"QPushButton[btnType=\"icon\"] {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton[btnType=\"icon\"]:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton[btnType=\"icon\"]:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"/* =============== LABELS ======================= */\n"
"QLabel {\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* =============== ENTRADAS DE TEXTO ============ */\n"
"QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    background-color: #2a2a2a;\n"
"    border: 1px solid #444;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #eee;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {\n"
"    border: 1px solid #00bcd4;\n"
"}\n"
"\n"
"/* =============== COMBOBOX ===================== */\n"
"QComboBox {\n"
"    background-color: #2a2a2a;\n"
"    border: 1px solid #444;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2a2a2a;\n"
"    selection-background-color: #00bcd4;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* =============== CHECKBOX ===================== */\n"
"QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #444;\n"
"    border: 1px solid #888;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #00bcd4;\n"
"    border: 1px solid #00bcd4;\n"
"}\n"
"\n"
"/* =============== SCROLLBARS =================== */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: #1e1e1e;\n"
"    border: none;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #555;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: #00bcd4;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listServers = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listServers.setGeometry(QtCore.QRect(30, 40, 431, 571))
        self.listServers.setObjectName("listServers")
        self.createServerBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.createServerBtn.setGeometry(QtCore.QRect(500, 540, 121, 61))
        self.createServerBtn.setObjectName("createServerBtn")
        self.configurePropertiesWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.configurePropertiesWidget.setGeometry(QtCore.QRect(490, 40, 691, 471))
        self.configurePropertiesWidget.setObjectName("configurePropertiesWidget")
        self.widgetWhiteList = QtWidgets.QWidget(parent=self.configurePropertiesWidget)
        self.widgetWhiteList.setGeometry(QtCore.QRect(350, 20, 351, 361))
        self.widgetWhiteList.setObjectName("widgetWhiteList")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widgetWhiteList)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 291, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layoutWhiteList = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.layoutWhiteList.setContentsMargins(0, 0, 0, 0)
        self.layoutWhiteList.setObjectName("layoutWhiteList")
        self.whiteList = QtWidgets.QListWidget(parent=self.layoutWidget)
        self.whiteList.setObjectName("whiteList")
        self.layoutWhiteList.addWidget(self.whiteList)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.nametagPlayer = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.nametagPlayer.setInputMask("")
        self.nametagPlayer.setText("")
        self.nametagPlayer.setObjectName("nametagPlayer")
        self.horizontalLayout_6.addWidget(self.nametagPlayer)
        self.buttonAddWhiteList = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.buttonAddWhiteList.setObjectName("buttonAddWhiteList")
        self.horizontalLayout_6.addWidget(self.buttonAddWhiteList)
        self.layoutWhiteList.addLayout(self.horizontalLayout_6)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.configurePropertiesWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 301, 416))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.portNumber = QtWidgets.QSpinBox(parent=self.layoutWidget1)
        self.portNumber.setWrapping(True)
        self.portNumber.setMinimum(1024)
        self.portNumber.setMaximum(65535)
        self.portNumber.setProperty("value", 25565)
        self.portNumber.setObjectName("portNumber")
        self.horizontalLayout.addWidget(self.portNumber)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.serverNameEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.serverNameEdit.setObjectName("serverNameEdit")
        self.horizontalLayout_2.addWidget(self.serverNameEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.players = QtWidgets.QSpinBox(parent=self.layoutWidget1)
        self.players.setWrapping(True)
        self.players.setMinimum(1)
        self.players.setMaximum(1000)
        self.players.setProperty("value", 20)
        self.players.setObjectName("players")
        self.horizontalLayout_3.addWidget(self.players)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.chunks = QtWidgets.QSpinBox(parent=self.layoutWidget1)
        self.chunks.setWrapping(True)
        self.chunks.setMinimum(4)
        self.chunks.setMaximum(32)
        self.chunks.setProperty("value", 10)
        self.chunks.setObjectName("chunks")
        self.horizontalLayout_4.addWidget(self.chunks)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.onlineMode = QtWidgets.QCheckBox(parent=self.layoutWidget1)
        self.onlineMode.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.onlineMode.setChecked(True)
        self.onlineMode.setObjectName("onlineMode")
        self.verticalLayout_3.addWidget(self.onlineMode)
        self.Whitelist = QtWidgets.QCheckBox(parent=self.layoutWidget1)
        self.Whitelist.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Whitelist.setChecked(False)
        self.Whitelist.setObjectName("Whitelist")
        self.verticalLayout_3.addWidget(self.Whitelist)
        self.pvp = QtWidgets.QCheckBox(parent=self.layoutWidget1)
        self.pvp.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pvp.setChecked(True)
        self.pvp.setObjectName("pvp")
        self.verticalLayout_3.addWidget(self.pvp)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.peacefulBtn = QtWidgets.QRadioButton(parent=self.layoutWidget1)
        self.peacefulBtn.setObjectName("peacefulBtn")
        self.verticalLayout.addWidget(self.peacefulBtn)
        self.easyBtn = QtWidgets.QRadioButton(parent=self.layoutWidget1)
        self.easyBtn.setChecked(True)
        self.easyBtn.setObjectName("easyBtn")
        self.verticalLayout.addWidget(self.easyBtn)
        self.normalBtn = QtWidgets.QRadioButton(parent=self.layoutWidget1)
        self.normalBtn.setObjectName("normalBtn")
        self.verticalLayout.addWidget(self.normalBtn)
        self.hardBtn = QtWidgets.QRadioButton(parent=self.layoutWidget1)
        self.hardBtn.setObjectName("hardBtn")
        self.verticalLayout.addWidget(self.hardBtn)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.survivalBtn = QtWidgets.QRadioButton(parent=self.layoutWidget1)
        self.survivalBtn.setChecked(True)
        self.survivalBtn.setObjectName("survivalBtn")
        self.verticalLayout_2.addWidget(self.survivalBtn)
        self.creativeBtn = QtWidgets.QRadioButton(parent=self.layoutWidget1)
        self.creativeBtn.setChecked(False)
        self.creativeBtn.setObjectName("creativeBtn")
        self.verticalLayout_2.addWidget(self.creativeBtn)
        self.adventureBtn = QtWidgets.QRadioButton(parent=self.layoutWidget1)
        self.adventureBtn.setObjectName("adventureBtn")
        self.verticalLayout_2.addWidget(self.adventureBtn)
        self.spectatorBtn = QtWidgets.QRadioButton(parent=self.layoutWidget1)
        self.spectatorBtn.setObjectName("spectatorBtn")
        self.verticalLayout_2.addWidget(self.spectatorBtn)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.saveProperties = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.saveProperties.setObjectName("saveProperties")
        self.verticalLayout_5.addWidget(self.saveProperties)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1392, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.createServerBtn.setText(_translate("MainWindow", "Create Server"))
        self.buttonAddWhiteList.setText(_translate("MainWindow", "ADD Player"))
        self.label.setText(_translate("MainWindow", "Server PORT:"))
        self.label_2.setText(_translate("MainWindow", "Server name:"))
        self.label_3.setText(_translate("MainWindow", "Server Players:"))
        self.label_4.setText(_translate("MainWindow", "Chunks"))
        self.onlineMode.setText(_translate("MainWindow", "Online mode"))
        self.Whitelist.setText(_translate("MainWindow", "White list"))
        self.pvp.setText(_translate("MainWindow", "PVP"))
        self.label_5.setText(_translate("MainWindow", "Difficulty:"))
        self.peacefulBtn.setText(_translate("MainWindow", "peaceful"))
        self.easyBtn.setText(_translate("MainWindow", "easy"))
        self.normalBtn.setText(_translate("MainWindow", "normal"))
        self.hardBtn.setText(_translate("MainWindow", "hard"))
        self.label_6.setText(_translate("MainWindow", "Game Mode:"))
        self.survivalBtn.setText(_translate("MainWindow", "Survival"))
        self.creativeBtn.setText(_translate("MainWindow", "Creative"))
        self.adventureBtn.setText(_translate("MainWindow", "Adventure"))
        self.spectatorBtn.setText(_translate("MainWindow", "Spectator"))
        self.saveProperties.setText(_translate("MainWindow", "SAVE"))
